version: '3.9'
services:
  mongodb:
    image: mongo:4.0.12
    volumes:
        - db-data:/data/db
    ports:
        - 27017:27017
  rabbitmq:
    image: rabbitmq
    ports:
        - 5672:5672
#   backend:
#     build: 
#         context: .
#         dockerfile: deploy/Dockerfile.backend
#     environment: 
#         MONGO_HOST: mongodb
#         RABBITMQ_HOST: rabbitmq
#     depends_on: 
#         - mongodb
#         - rabbitmq
#     ports:
#         - 8080:8080
volumes:
    db-data: