export const texts = {
    "navbar.title": "TON STATUS",
    "tps.block_rate": "Blocks per second",
    "tps.block_rate.basechain": "basechain",
    "tps.block_rate.masterchain": "masterchain",
    "tps.tps": "transactions per second",
    "tps.shardchains": "shardchains",
    "tps.validators.online": "online",
    "tps.validators.total": "total",
    "tps.validators": "Validators",
    "governance.title": "Governance status",
    "governance.election": "Election status",
    "governance.election.closes": "Closes",
    "governance.election.starts": "Starts",
    "governance.election.next_starts": "Next starts",
    "governance.offers": "Offers",
    "governance.complaints": "Complaints",
    "uptime.uptime": "uptime",
    "uptime.response_time": "response time",
    "tonbridges.title": "TON bridges",
    "tonbridges.available": "Available",
    "tonbridges.not_available": "Not available",
    "lastblock.title": "Last block",
    "lastblock.masterchain": "Masterchain",
    "lastblock.basechain": "Basechain",
    "transactionstats.title": "Transaction types (24 hours)",
} as { [key: string]: string };