FROM ubuntu:20.04

# install python
ENV DEBIANFRONTEND=noninteractive
RUN apt-get --yes update
RUN apt-get --yes install python3-dev python3-pip python3-wheel

# install python libraries
RUN pip3 install -U pip wheel
ADD requirements.txt /tmp/requirements.txt
RUN pip3 install -r /tmp/requirements.txt

# entrypoint
ADD . /usr/src/app

WORKDIR /usr/src/app
EXPOSE 8080
ENTRYPOINT ["python3", "./run_web_server.py"]
