FROM ubuntu:20.04

# setup locale and timezone
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y locales
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=en_US.UTF-8
ENV LANG en_US.UTF-8 

# install python
ENV DEBIANFRONTEND=noninteractive
RUN apt-get --yes update
RUN apt-get --yes install python3-dev python3-pip python3-wheel
RUN apt-get --yes install gcc g++ cmake make

# install python libraries
RUN pip3 install -U pip wheel
ADD requirements.txt /tmp/requirements.txt
RUN pip3 install -r /tmp/requirements.txt

# entrypoint
ADD . /usr/src/app

WORKDIR /usr/src/app
EXPOSE 8080

ENTRYPOINT ["python3", "./run_web_server.py", "--ip", "0.0.0.0", "--port", "8080"]
